# Generated by Django 5.2.9 on 2026-01-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_no', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('base_salary', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
            ],
        ),
    ]
