# Generated by Django 5.2.9 on 2026-01-05 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lpo_no', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lpos', to='invoices.customer')),
            ],
        ),
        migrations.CreateModel(
            name='LPOItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=30)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('lpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lpo.lpo')),
                ('warehouse_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.warehouseitem')),
            ],
        ),
    ]
