# Generated by Django 5.2.9 on 2026-01-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('unit_label', models.CharField(default='piece', max_length=50)),
                ('price', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('stock_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('item_type', models.CharField(choices=[('fixed', 'Fixed'), ('per_meter', 'Per meter')], default='fixed', max_length=20)),
            ],
        ),
    ]
