# Generated by Django 5.2.9 on 2026-01-07 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_no', models.AutoField(primary_key=True, serialize=False)),
                ('warehouse_name', models.CharField(max_length=200)),
                ('warehouse_location', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='warehouseitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.warehouse'),
        ),
    ]
