# Generated by Django 5.2.9 on 2026-01-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('IN_REPAIR', 'In repair'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
