# Generated by Django 5.2.9 on 2026-01-07 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_add_asset_fields'),
        ('warehouse', '0002_warehouse_warehouseitem_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='category',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='purchase_date',
        ),
        migrations.AlterField(
            model_name='asset',
            name='code',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.warehouse'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('IN_REPAIR', 'In repair'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=20),
        ),
    ]
